### ISSUE TITLE
Support for Rails 6

### ISSUE THREAD

**Issue by JGrishey** [jarthod/survey-gizmo-ruby#108]
Will this gem be updated to support the use of Rails 6?

**Comment by jarthod** [comment]
What's the problem with Rails 6? `activesupport` dependency I guess? if you can loosen it and try it on Rails 6 that would be helpful ;)

**Comment by JGrishey** [comment]
Opened #109 😄

**Comment by jarthod** [comment]
Thanks! released `7.1.0`
