### ISSUE TITLE
"NameError: uninitialized constant Module::Net" when attempting to configure

### ISSUE THREAD

**Issue by kjhenner** [jarthod/survey-gizmo-ruby#57]
>> require 'survey-gizmo-ruby'
    => true
    >> SurveyGizmo.configure{ |c| c.user = 'test' }
    NameError: uninitialized constant Module::Net
            from /Users/Henner/.rvm/gems/ruby-2.2.2/gems/survey-gizmo-ruby-5.0.2/lib/survey_gizmo/configuration.rb:50:in `retryables'
            from /Users/Henner/.rvm/gems/ruby-2.2.2/gems/survey-gizmo-ruby-5.0.2/lib/survey_gizmo/configuration.rb:31:in `configure_pester'
            from /Users/Henner/.rvm/gems/ruby-2.2.2/gems/survey-gizmo-ruby-5.0.2/lib/survey_gizmo/configuration.rb:13:in `configure'
            from (irb):2
            from /Users/Henner/.rvm/rubies/ruby-2.2.2/bin/irb:11:in `<main>'

**Comment by kjhenner** [comment]
Requiring 'net/http' fixes the issue. Am I missing some aspect of the configuration that would set this up?

**Comment by jarthod** [comment]
I can't reproduce this, can you specify which version of `ruby` you're using ?

**Comment by apurvis** [comment]
i can't reproduce this either - i would expect that net/http would be loaded by [faraday](https://github.com/lostisland/faraday) because it is the default http adapter

**Comment by apurvis** [comment]
i was able to reproduce this by running `irb` instead of `bundle exec irb`. this is not actually a bug; you just didn't start irb the right way.

**Comment by kjhenner** [comment]
Got it, thanks!
