### ISSUE TITLE
Creation of SG objects doesn't retry correctly

### ISSUE THREAD

**Issue by apurvis** [jarthod/survey-gizmo-ruby#60]
I noticed when working on another gem that Faraday doesn't reencode the JSON of a `POST` body if the retry is in the middleware stack.

I don't use this feature at all so I won't be fixing it; just marking this issue in case others run into this problem and want to fix it.  

You'll see a `bytesize not defined on object` error when Net::HTTP tries to encode the pre-JSON encoded hash if you run into this.

**Comment by jarthod** [comment]
Thanks, is this a bug in faraday or in our middleware stack ?

**Comment by apurvis** [comment]
i think it's a bug in my implementation but i'm not sure.  you might be able to initialize the `@app` in the middleware and then do `@app.call` on a retry which _might_ pass the request back through all the layers of middleware, but i'm not sure and i'm not going to figure it out because i don't use this feature.

**Comment by apurvis** [comment]
actually nevermind; that's [what we already do](https://github.com/jarthod/survey-gizmo-ruby/blob/master/lib/survey_gizmo/faraday_middleware/pester_survey_gizmo.rb#L10)

the problem is that `@app.call` doesn't pass the request through the other middlewares, [some of which](https://github.com/jarthod/survey-gizmo-ruby/blob/master/lib/survey_gizmo/connection.rb#L30) are critical.

we could do the json encode/decode in our own middleware but... blech.  or maybe extend the JSON middleware - again, i dunno.  

the other option is to move the retries out of the middleware altogether, but then that means you have to wrap the `post`, `get`, etc methods, which is kinda... blech.

i'm assuming there has got to be a good answer for this because it seems inconceivable that you can't get faraday to do a retry from within middleware - that's like half the point of middleware, to let you respond mid flow - but i just don't know what it is.

anyways the temporary workaround would be to set the number of retries to 1 in a situation where you are POSTing data.  it actually won't solve anything - you'll get an exception still, but at least it will be the right exception and not the `.bytesize not defined` one.

**Comment by jarthod** [comment]
Ok interesting, it should work this way AFAIK.
What if we just move the json middleware up in the stack (above pester) ?
It may impact logging but maybe it'll work better ?

**Comment by apurvis** [comment]
I think I tried this but I forgot.  Might work?
