### ISSUE TITLE
get an IP address from a given response

### ISSUE THREAD

**Issue by ZainW** [jarthod/survey-gizmo-ruby#63]
Is there a way to get the IP address from a response? 

It is an available callback found [here](https://apihelp.surveygizmo.com/help/article/link/surveyresponse-returned-fields) I was wondering if maybe that could be implemented as it is needed to authenticate responses for my project.

**Comment by ZainW** [comment]
I actually ended up finding a way, so here is my next step i guess, which is figuring out how to contribute to the gem in a proper professional way. I will reserve that for a later date by adding the meta class which contains things like IP, various location attributes, device type and useragent info. 

sorry for the useless posts

**Comment by jarthod** [comment]
Hi @ZainW, fell free to just paste your code here if you don't want to loose time doing a pull request, so someone else may do it :)

**Comment by ZainW** [comment]
Sure thing,

If you would like to get some of the meta information for any given response, grab a response then run `response.meta` to get a hash of the data, if you want specific data with a return, pass the appropriate symbol eg `response.meta[:ip]` to get the IP address of the user. I also used this to get location data without having to take a user input and trusting that is where they are from.

**Comment by jarthod** [comment]
Ok great, so the data is already fetched and accessible. Is there anything to add to the gem then?
