### ISSUE TITLE
How to avoid "WARN Have to do individual load of sub question"?

### ISSUE THREAD

**Issue by tisba** [jarthod/survey-gizmo-ruby#69]
I just got the time to work on a project again involving survey gizmo. I need to fetch all questions and I get a lot of the following warnings just by calling `survey#questions`:

```
2016-05-15 20:21:53 WARN Have to do individual load of sub question 4...
2016-05-15 20:21:53 WARN Have to do individual load of sub question 5...
2016-05-15 20:21:54 WARN Have to do individual load of sub question 18...
…
```

I don't really understand what I should do instead (assuming that the warning tells me that I should not load the sub questions individually).

**Comment by jarthod** [comment]
@FabienChaynes Wasn't this some debug ?

**Comment by apurvis** [comment]
the only thing you can do about it is write to surveygizmo to complain about the bug where they don't return the subquestions to a standard request for questions for a survey.

as a consequence, we have to make individual API calls for every single question to make sure we really have all the questions.  this dramatically increases the likelihood of SG barfing on a rate limit exceeded error and is generally just a bad situation created by a bug in their API.

**Comment by apurvis** [comment]
https://github.com/jarthod/survey-gizmo-ruby/blob/master/lib/survey_gizmo/resource.rb#L52-L56

**Comment by tisba** [comment]
Okay, I get that the SG API lags support for this.

But I have to say, that this warning is not useful at best. As a gem user I cannot do anything about that and it will spam my log with messages. IMO, if you want to make users aware of this issue, it should go to the README or as a post-install message.

**Comment by jarthod** [comment]
I suggest we just move the log level of this line to debug, so you can ignore it simply by using a higher loglevel, which is definitely recommended in production. WDYT ?

**Comment by apurvis** [comment]
moving to DEBUG level sounds fair

**Comment by apurvis** [comment]
that said @tisba you can do something about it - complain to surveygizmo and get them to fix it!

**Comment by tisba** [comment]
Sure I send a service request, let's see what they have to say about it :)

**Comment by apurvis** [comment]
in theory they opened a ticket for this issue many months ago when i spoke to them

**Comment by jarthod** [comment]
Ok I've just released `6.1.2` with the fix.

**Comment by tisba** [comment]
Thanks! btw, @apurvis, SG support told me, that they are working on it for v5.

**Comment by apurvis** [comment]
good to know; thanks.
