### ISSUE TITLE
Support activesupport 5.0

### ISSUE THREAD

**Issue by mkilling** [jarthod/survey-gizmo-ruby#89]
Currently this gem depends on activesupport < 5.0 which makes it incompatible with Rails 5. It would be great if it would work with activesupport 5.0 as well.

**Comment by apurvis** [comment]
there were some issues integrating with 5.0 when it was released, which is why we have the version restriction. it's not on my roadmap to fix it but feel free to open a PR.

**Comment by tisba** [comment]
Can you recall what the issue was about, @apurvis?

**Comment by apurvis** [comment]
unfortunately i cannot remember...

**Comment by apurvis** [comment]
i think it was just that the specs were failing... i don't think I got far enough in the process to determine whether functionality was affected (beyond the specs) because we won't be upgrading to rails 5.0 for at least a year.

**Comment by apurvis** [comment]
@tisba maybe the problem was that rails 5 requires ruby 2.2.2?

**Comment by jmcnevin** [comment]
FWIW, I was able to bump that activesupport version requirement to `< 5.1` on my fork, and the specs ran fine (with ruby 2.3.1p112), granted, with some noisy output: https://gist.github.com/jmcnevin/c27414e8acf723cf215716bee7f9fd18

**Comment by apurvis** [comment]
how about actual usage?

**Comment by apurvis** [comment]
https://github.com/jarthod/survey-gizmo-ruby/pull/99
