### ISSUE TITLE
Rails 5 Deprecation: alias_method_chain

### ISSUE THREAD

**Issue by tisba** [jarthod/survey-gizmo-ruby#95]
`alias_method_chain` has been deprecated.

As far as I can tell it is only used in [one place](https://github.com/jarthod/survey-gizmo-ruby/blob/afeee48618d7727fa9591bb635c53d5005bd0cee/lib/survey_gizmo/multilingual_title.rb#L8) and should be easily replaceable.

**Comment by jarthod** [comment]
Indeed, feel free to submit a PR ;)

**Comment by tisba** [comment]
done :)

**Comment by jarthod** [comment]
Thanks!
